// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deployments.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDeployment = `-- name: CreateDeployment :one
INSERT INTO deployments (
    project_id,
    status
)
VALUES (
    $1,
    $2
)
RETURNING id, project_id, status, created_at, port
`

type CreateDeploymentParams struct {
	ProjectID int32
	Status    string
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, createDeployment, arg.ProjectID, arg.Status)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Status,
		&i.CreatedAt,
		&i.Port,
	)
	return i, err
}

const deleteDeployment = `-- name: DeleteDeployment :exec
DELETE FROM deployments
WHERE id = $1
`

func (q *Queries) DeleteDeployment(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteDeployment, id)
	return err
}

const deleteDeploymentsByProject = `-- name: DeleteDeploymentsByProject :exec
DELETE FROM deployments
WHERE project_id = $1
`

func (q *Queries) DeleteDeploymentsByProject(ctx context.Context, projectID int32) error {
	_, err := q.db.Exec(ctx, deleteDeploymentsByProject, projectID)
	return err
}

const getDeployment = `-- name: GetDeployment :one
SELECT id, project_id, status, created_at, port
FROM deployments
WHERE id = $1
`

func (q *Queries) GetDeployment(ctx context.Context, id int32) (Deployment, error) {
	row := q.db.QueryRow(ctx, getDeployment, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Status,
		&i.CreatedAt,
		&i.Port,
	)
	return i, err
}

const getDeployments = `-- name: GetDeployments :many
SELECT id, project_id, status, created_at, port
FROM deployments
ORDER BY created_at DESC
`

func (q *Queries) GetDeployments(ctx context.Context) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, getDeployments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Status,
			&i.CreatedAt,
			&i.Port,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeploymentsByProject = `-- name: GetDeploymentsByProject :many
SELECT id, project_id, status, created_at, port
FROM deployments
WHERE project_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetDeploymentsByProject(ctx context.Context, projectID int32) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, getDeploymentsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Status,
			&i.CreatedAt,
			&i.Port,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeploymentPort = `-- name: UpdateDeploymentPort :exec
UPDATE deployments
SET port = $2
WHERE id = $1
`

type UpdateDeploymentPortParams struct {
	ID   int32
	Port pgtype.Int4
}

func (q *Queries) UpdateDeploymentPort(ctx context.Context, arg UpdateDeploymentPortParams) error {
	_, err := q.db.Exec(ctx, updateDeploymentPort, arg.ID, arg.Port)
	return err
}

const updateDeploymentStatus = `-- name: UpdateDeploymentStatus :one
UPDATE deployments
SET status = $2
WHERE id = $1
RETURNING id, project_id, status, created_at, port
`

type UpdateDeploymentStatusParams struct {
	ID     int32
	Status string
}

func (q *Queries) UpdateDeploymentStatus(ctx context.Context, arg UpdateDeploymentStatusParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, updateDeploymentStatus, arg.ID, arg.Status)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Status,
		&i.CreatedAt,
		&i.Port,
	)
	return i, err
}
