// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Deployment struct {
	ID        int32
	ProjectID int32
	Status    string
	CreatedAt pgtype.Timestamp
	Port      pgtype.Int4
}

type Project struct {
	ID        int32
	Name      string
	RepoUrl   string
	CreatedAt pgtype.Timestamp
	UserID    pgtype.Int4
}

type User struct {
	ID           int32
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamp
}
