// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_environment.sql

package database

import (
	"context"
)

const deleteProjectEnvVar = `-- name: DeleteProjectEnvVar :exec
DELETE FROM project_env_vars
WHERE project_id = $1 AND name = $2
`

type DeleteProjectEnvVarParams struct {
	ProjectID int32
	Name      string
}

func (q *Queries) DeleteProjectEnvVar(ctx context.Context, arg DeleteProjectEnvVarParams) error {
	_, err := q.db.Exec(ctx, deleteProjectEnvVar, arg.ProjectID, arg.Name)
	return err
}

const listProjectEnvVars = `-- name: ListProjectEnvVars :many
SELECT name, encrypted_value
FROM project_env_vars
WHERE project_id = $1
ORDER BY name
`

type ListProjectEnvVarsRow struct {
	Name           string
	EncryptedValue []byte
}

func (q *Queries) ListProjectEnvVars(ctx context.Context, projectID int32) ([]ListProjectEnvVarsRow, error) {
	rows, err := q.db.Query(ctx, listProjectEnvVars, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectEnvVarsRow
	for rows.Next() {
		var i ListProjectEnvVarsRow
		if err := rows.Scan(&i.Name, &i.EncryptedValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProjectEnvVar = `-- name: UpsertProjectEnvVar :exec
INSERT INTO project_env_vars (project_id, name, encrypted_value)
VALUES ($1, $2, $3)
ON CONFLICT (project_id, name)
DO UPDATE SET encrypted_value = EXCLUDED.encrypted_value, updated_at = NOW()
`

type UpsertProjectEnvVarParams struct {
	ProjectID      int32
	Name           string
	EncryptedValue []byte
}

func (q *Queries) UpsertProjectEnvVar(ctx context.Context, arg UpsertProjectEnvVarParams) error {
	_, err := q.db.Exec(ctx, upsertProjectEnvVar, arg.ProjectID, arg.Name, arg.EncryptedValue)
	return err
}
