// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
    name,
    repo_url,
    user_id
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id, name, repo_url, created_at, user_id
`

type CreateProjectParams struct {
	Name    string
	RepoUrl string
	UserID  pgtype.Int4
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.Name, arg.RepoUrl, arg.UserID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RepoUrl,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}

const deleteProjectByUser = `-- name: DeleteProjectByUser :exec
DELETE FROM projects
WHERE id = $1
AND user_id = $2
`

type DeleteProjectByUserParams struct {
	ID     int32
	UserID pgtype.Int4
}

func (q *Queries) DeleteProjectByUser(ctx context.Context, arg DeleteProjectByUserParams) error {
	_, err := q.db.Exec(ctx, deleteProjectByUser, arg.ID, arg.UserID)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, name, repo_url, created_at, user_id
FROM projects
WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id int32) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RepoUrl,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}

const getProjectByUser = `-- name: GetProjectByUser :one
SELECT id, name, repo_url, created_at, user_id
FROM projects
WHERE id = $1
AND user_id = $2
`

type GetProjectByUserParams struct {
	ID     int32
	UserID pgtype.Int4
}

func (q *Queries) GetProjectByUser(ctx context.Context, arg GetProjectByUserParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByUser, arg.ID, arg.UserID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RepoUrl,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}

const getProjectsByUser = `-- name: GetProjectsByUser :many
SELECT id, name, repo_url, created_at, user_id
FROM projects
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetProjectsByUser(ctx context.Context, userID pgtype.Int4) ([]Project, error) {
	rows, err := q.db.Query(ctx, getProjectsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RepoUrl,
			&i.CreatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
