// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package database

import (
	"context"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
    name,
    repo_url
)
VALUES (
    $1,
    $2
)
RETURNING id, name, repo_url, created_at
`

type CreateProjectParams struct {
	Name    string
	RepoUrl string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.Name, arg.RepoUrl)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RepoUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getProjects = `-- name: GetProjects :many
SELECT id, name, repo_url, created_at
FROM projects
ORDER BY created_at DESC
`

func (q *Queries) GetProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, getProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RepoUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
